defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/launcher: ray

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: sphere
    storage: null
    n_trials: 10
    n_jobs: 10
    max_failure_rate: 0.0
    params:
      loss.gamma: choice(0.95, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99)
  launcher:
    ray:
      remote:
        num_gpus: 0.5
        num_cpus: 8

env:
  env_name: crafter
  num_envs: 8
  category: crafter

# collector
collector:
  frames_per_batch: 8192
  total_frames: 40_000_000

# logger
logger:
  backend: wandb
  project_name: ppo_concepts
  group_name: null
  exp_name: Crafter_Concepts
  test_interval: 40_000
  num_test_episodes: 3

# Optim
optim:
  lr: 3.0e-4
  eps: 1.0e-6
  weight_decay: 0.0
  max_grad_norm: 0.5
  anneal_lr: True

# loss
loss:
  gamma: 0.95
  mini_batch_size: 1024
  ppo_epochs: 3
  gae_lambda: 0.65
  clip_epsilon: 0.2
  anneal_clip_epsilon: True
  critic_coef: 0.5
  entropy_coef: 0.01
  loss_critic_type: l2
  concept_coef: 0.0
  model: impala
