defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/launcher: ray

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: sphere
    storage: null
    n_trials: 81
    n_jobs: 48
    max_failure_rate: 0.0
    params:
      loss.model_params.posenc_n_layers: choice(2,3, 4)
      loss.model_params.joint_n_layers: choice(1,2, 3)
      loss.model_params.history_n_layers: choice(1,2, 3)
      loss.model_params.status_n_layers: choice(1,2, 3)
  launcher:
    ray:
      remote:
        num_gpus: 0.25
        num_cpus: 8

env:
  env_name: crafter
  num_envs: 8
  category: crafter
  task: default

# collector
collector:
  frames_per_batch: 4096
  total_frames: 2_000_000

# logger
logger:
  backend: wandb
  project_name: ppo_concepts
  group_name: null
  exp_name: Crafter_Concepts
  test_interval: 40_000
  num_test_episodes: 3

# Optim
optim:
  lr: 3.0e-4
  eps: 1.0e-6
  weight_decay: 0.0
  max_grad_norm: 0.5
  anneal_lr: True
  anneal_milestones: [0.15, 0.66, 0.9, 2.0]
  anneal_lrs: [3e-4, 2e-4, 15e-5, 5e-5]
  annealing_end_batch: 244

# loss
loss:
  gamma: 0.95
  mini_batch_size: 512
  ppo_epochs: 3
  gae_lambda: 0.65
  clip_epsilon: 0.2
  anneal_clip_epsilon: False
  critic_coef: 0.5
  entropy_coef: 0.01
  loss_critic_type: l2
  concept_coef: 0.0
  model: impala_achievements
  model_params:
    joint_n_layers: 2
    posenc_n_layers: 2
    history_n_layers: 2
    status_n_layers: 2
    use_pixels: False
